### ISSUE TITLE
Week 02 回覆

### ISSUE THREAD

**Issue by azole** [yun-si/git-practice#2]
## Readme

非常好喲，已經寫到這週的作業了 👍

## Sum

你分別用了 forEach 跟 reduce，你覺得哪個比較恰當呢？

## Fib
很好，不過程式碼好像可以再更好讀一點，也就是邏輯上可以再更清晰，上課的時候一起討論看看。

Fib 應該也不只有這種寫法，還有什麼可能性嗎?

## Stack

stack 跟測試案例都很好

一個非常小的地方「pop when stack is null」 => null 跟 empty 是不一樣的

整體 coding style 也合格，很不錯！

**Comment by yun-si** [comment]
## Sum
`forEach` 對於熟悉迴圈的我來說比較直觀好懂，但針對 sum 這樣累加的問題，reduce 的設計感覺更合適，因為傳進 reduce 的函式，參數就有一個 accumulator 。從兩個寫法來看，達到同一個目的，使用 reduce的也更加簡潔。

## Fib
聽完課後有試著修改原本的寫法

有想到另一個寫法：n多少就把array加到多長（有多新增一個 commit 把下面這段加上去）
```js
let fibonacci1 = (n) => {
    let arr = [];
    arr[0] = 0;
    arr[1] = 1;
    for (let i=2; i<=n; i++) {
        arr[n] = arr[n-1] + arr[n-2]
    }
    return arr[n]
}
```

印前十個的結果
```
[
  0, 1,  1,  2,  3,
  5, 8, 13, 21, 34
]
```
雖然 n 越大 arr 需要的空間就會越多，但看起來更好讀
## Stack
☺️

> 一個非常小的地方「pop when stack is null」 => null 跟 empty 是不一樣的

寫的時候沒有注意到，有更改了

**Comment by azole** [comment]
ok 這個 issue 可以 close 了
